#!/bin/bash
 
MASTER=$1

echo "10m a"
./test $MASTER 10m Y A
./test $MASTER 10m Y A
./test $MASTER 10m Y A
./test $MASTER 10m Y A
./test $MASTER 10m Y A
./test $MASTER 10m Y A

echo "10m b"
./test $MASTER 10m Y B
./test $MASTER 10m Y B
./test $MASTER 10m Y B
./test $MASTER 10m Y B
./test $MASTER 10m Y B
./test $MASTER 10m Y B

echo "10m C"
./test $MASTER 10m Y C
./test $MASTER 10m Y C
./test $MASTER 10m Y C
./test $MASTER 10m Y C
./test $MASTER 10m Y C
./test $MASTER 10m Y C

echo "100m a"
./test $MASTER 100m Y A
./test $MASTER 100m Y A
./test $MASTER 100m Y A
./test $MASTER 100m Y A
./test $MASTER 100m Y A
./test $MASTER 100m Y A

echo "100m b"
./test $MASTER 100m Y B
./test $MASTER 100m Y B
./test $MASTER 100m Y B
./test $MASTER 100m Y B
./test $MASTER 100m Y B
./test $MASTER 100m Y B

echo "100m c"
./test $MASTER 100m Y C
./test $MASTER 100m Y C
./test $MASTER 100m Y C
./test $MASTER 100m Y C
./test $MASTER 100m Y C
./test $MASTER 100m Y C

echo "1g a"
./test $MASTER 1g Y A
./test $MASTER 1g Y A
./test $MASTER 1g Y A
./test $MASTER 1g Y A
./test $MASTER 1g Y A
./test $MASTER 1g Y A

echo "1g b"
./test $MASTER 1g Y B
./test $MASTER 1g Y B
./test $MASTER 1g Y B
./test $MASTER 1g Y B
./test $MASTER 1g Y B
./test $MASTER 1g Y B

echo "1g c"
./test $MASTER 1g Y C
./test $MASTER 1g Y C
./test $MASTER 1g Y C
./test $MASTER 1g Y C
./test $MASTER 1g Y C
./test $MASTER 1g Y C

echo "10g b"
./test $MASTER 10g Y B
./test $MASTER 10g Y B
./test $MASTER 10g Y B
./test $MASTER 10g Y B

echo "10g c"
./test $MASTER 10g Y C
./test $MASTER 10g Y C
./test $MASTER 10g Y C
